version: '3'
services:
        web:
                image: flask_keira_v1
                build: .
                ports:
<<<<<<< HEAD
                        - "8046:8080"
=======
                        - "8039:8080"
>>>>>>> 6f4a8af510a157c5ca38b3f24e9aa29e58c59264
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/keira_flask_portfolio/volumes
